# Generated by Django 5.2.4 on 2025-07-23 23:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resena', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.libro')),
            ],
        ),
    ]
